export 'package:app_flutter_1/screens/alert_screen.dart';
export 'package:app_flutter_1/screens/animated_screen.dart';
export 'package:app_flutter_1/screens/avatar_screen.dart';
export 'package:app_flutter_1/screens/card_screen.dart';
export 'package:app_flutter_1/screens/HomeScreen.dart';
export 'package:app_flutter_1/screens/input_screen.dart';
export 'package:app_flutter_1/screens/listview_builder_screen.dart';
export 'package:app_flutter_1/screens/listview1_screen.dart';
export 'package:app_flutter_1/screens/slider_screen.dart';
